---
title: "Copula"
output: html_notebook
---

```{r}
library(readr)
library(dynlm)
library(normtest)
library(car) 
library(lmtest)
library(REndo)

### Testing model for problems
testing.model <- function(model) {
  cat("--==Testing model==--", fill = T)
  cat(fill = T)
  cat("R-squared:", summary(model)$r.squared, fill = T)
  cat("Adj. R-squared:", summary(model)$adj.r.squared, fill = T)
  cat("AIC: ", AIC(model), fill = T)
  cat(fill = T)
  cat("Normality of disturbances: ", jb.norm.test(model$residuals)$p.value, fill = T)
  cat(fill = T)
  cat("Multicollinearity: ", max(vif(model)), fill = T)
  cat(fill = T)
  cat("Heteroskedasticity: ", bptest(model)$p.value, fill = T)
  cat(fill = T)
  cat("Autocorrelation of 1 order: ", bgtest(model)$p.value, fill = T)
  cat(fill = T)
  cat("RESET-test: ", reset(model)$p.value, fill = T)
}


```

# Russia

## Importing data

```{r}
dataRF <- read_csv("C://R//Data//dataRF.csv", col_types = cols(Date = col_character()))
dataRF$perSIDinNGDP <- dataRF$SID*100/dataRF$NGDP
dataRF$LUNEMPL <- c(5.9, dataRF$UNEMPL[-45])
dataRF$LNPLp <- c(1.76780823887159, dataRF$NPLp[-45])
```

## OLS model

```{r}
mdlRF <- lm(data=dataRF, formula = NPLp ~ LUNEMPL + bvCrisis + perSIDinNGDP + indexDemocracy + indexInstitute + indexPayment + LNPLp)
summary(mdlRF)
testing.model(mdlRF)
```


## Copula regression

```{r include=FALSE}

# Adjust randomness
set.seed(1234)

cplRF <- copulaCorrection(formula =  NPLp ~ LUNEMPL + bvCrisis + perSIDinNGDP + indexDemocracy + indexInstitute + indexPayment + LNPLp | continuous(perSIDinNGDP, indexPayment, indexInstitute), num.boots = 10000, data=dataRF)
```

```{r}
options(scipen=2)
summary(cplRF)
```

```{r}
jb.norm.test(cplRF$residuals)
acf(cplRF$residuals)
bptest(cplRF)
bgtest(cplRF, order = 2)
bptest(cplRF)
reset(cplRF)
```

# Kazakhstan

## Importing data

```{r}
dataKZ <- read_csv("C://R//Data//dataKZ.csv", col_types = cols(Date = col_character()))
dataKZ$perSIDinNGDP <- dataKZ$SID*100/dataKZ$NGDP
dataKZ$LUNEMPL <- c(5.5, dataKZ$Unempl[-36])
dataKZ$LNPLp <- c(14.6071858314849, dataKZ$NPLp[-36])
```


## OLS model

```{r}
mdlKZ <- lm(data=dataKZ, formula = NPLp ~ LUNEMPL + perSIDinNGDP + indexDemocracy + indexInstitute + indexPayment + LNPLp)
summary(mdlKZ)
testing.model(mdlKZ)
```

## Copula regression

```{r include=FALSE}

# Adjust randomness
set.seed(1234)

cplKZ <- copulaCorrection(formula =  NPLp ~ LUNEMPL + perSIDinNGDP + indexDemocracy + indexInstitute + indexPayment + LNPLp | continuous(perSIDinNGDP, indexPayment, indexInstitute), num.boots = 10000, data=dataKZ)
```

```{r}
options(scipen=2)
summary(cplKZ)
```

```{r}
jb.norm.test(cplKZ$residuals)
acf(cplKZ$residuals)
bptest(cplKZ)
bgtest(cplKZ, order = 2)
bptest(cplKZ)
reset(cplKZ)
```